/**@file	本文件存放事件id对应的事件名称的常量数组
 *
 */

#include "event_id.h"

const char*	pm_evt_id[22] = {
	"PM_EVT_BONDED_PEER_CONNECTED",
	"PM_EVT_CONN_CONFIG_REQ",
	"PM_EVT_CONN_SEC_START",
	"PM_EVT_CONN_SEC_SUCCEEDED",
	"PM_EVT_CONN_SEC_FAILED",
	"PM_EVT_CONN_SEC_CONFIG_REQ",
	"PM_EVT_CONN_SEC_PARAMS_REQ",
	"PM_EVT_STORAGE_FULL",
	"PM_EVT_ERROR_UNEXPECTED",
	"PM_EVT_PEER_DATA_UPDATE_SUCCEEDED",
	"PM_EVT_PEER_DATA_UPDATE_FAILED",
	"PM_EVT_PEER_DELETE_SUCCEEDED",
	"PM_EVT_PEER_DELETE_FAILED",
	"PM_EVT_PEERS_DELETE_SUCCEEDED",
	"PM_EVT_PEERS_DELETE_FAILED",
	"PM_EVT_LOCAL_DB_CACHE_APPLIED",
	"PM_EVT_LOCAL_DB_CACHE_APPLY_FAILED",
	"PM_EVT_SERVICE_CHANGED_IND_SENT",
	"PM_EVT_SERVICE_CHANGED_IND_CONFIRMED",
	"PM_EVT_SLAVE_SECURITY_REQ",
	"PM_EVT_FLASH_GARBAGE_COLLECTED",
	"PM_EVT_FLASH_GARBAGE_COLLECTION_FAILED"
};

const char* ble_evt_id[89] = {
	"BLE_EVT_INVALID",
	"BLE_EVT_USER_MEM_REQUEST",
	"BLE_EVT_USER_MEM_RELEASE",
	"NULL3",
	"NULL4",
	"NULL5",
	"NULL6",
	"NULL7",
	"NULL8",
	"NULL9",
	"NULL10",
	"NULL11",
	"NULL12",
	"NULL13",
	"NULL14",
	"NULL15",
	"BLE_GAP_EVT_CONNECTED",
	"BLE_GAP_EVT_DISCONNECTED",
	"BLE_GAP_EVT_CONN_PARAM_UPDATE",
	"BLE_GAP_EVT_SEC_PARAMS_REQUEST",
	"BLE_GAP_EVT_SEC_INFO_REQUEST",
	"BLE_GAP_EVT_PASSKEY_DISPLAY",
	"BLE_GAP_EVT_KEY_PRESSED",
	"BLE_GAP_EVT_AUTH_KEY_REQUEST",
	"BLE_GAP_EVT_LESC_DHKEY_REQUEST",
	"BLE_GAP_EVT_AUTH_STATUS",
	"BLE_GAP_EVT_CONN_SEC_UPDATE",
	"BLE_GAP_EVT_TIMEOUT",
	"BLE_GAP_EVT_RSSI_CHANGED",
	"BLE_GAP_EVT_ADV_REPORT",
	"BLE_GAP_EVT_SEC_REQUEST",
	"BLE_GAP_EVT_CONN_PARAM_UPDATE_REQUEST",
	"BLE_GAP_EVT_SCAN_REQ_REPORT",
	"BLE_GAP_EVT_PHY_UPDATE_REQUEST",
	"BLE_GAP_EVT_PHY_UPDATE",
	"BLE_GAP_EVT_DATA_LENGTH_UPDATE_REQUEST",
	"BLE_GAP_EVT_DATA_LENGTH_UPDATE",
	"BLE_GAP_EVT_QOS_CHANNEL_SURVEY_REPORT",
	"BLE_GAP_EVT_ADV_SET_TERMINATED",
	"NULL39",
	"NULL40",
	"NULL41",
	"NULL42",
	"NULL43",
	"NULL44",
	"NULL45",
	"NULL46",
	"NULL47",
	"BLE_GATTC_EVT_PRIM_SRVC_DISC_RSP",
	"BLE_GATTC_EVT_REL_DISC_RSP",
	"BLE_GATTC_EVT_CHAR_DISC_RSP",
	"BLE_GATTC_EVT_DESC_DISC_RSP",
	"BLE_GATTC_EVT_ATTR_INFO_DISC_RSP",
	"BLE_GATTC_EVT_CHAR_VAL_BY_UUID_READ_RSP",
	"BLE_GATTC_EVT_READ_RSP",
	"BLE_GATTC_EVT_CHAR_VALS_READ_RSP",
	"BLE_GATTC_EVT_WRITE_RSP",
	"BLE_GATTC_EVT_HVX",
	"BLE_GATTC_EVT_EXCHANGE_MTU_RSP",
	"BLE_GATTC_EVT_TIMEOUT",
	"BLE_GATTC_EVT_WRITE_CMD_TX_COMPLETE",
	"NULL61",
	"NULL62",
	"NULL63",
	"NULL64",
	"NULL65",
	"NULL66",
	"NULL67",
	"NULL68",
	"NULL69",
	"NULL70",
	"NULL71",
	"NULL72",
	"NULL73",
	"NULL74",
	"NULL75",
	"NULL76",
	"NULL77",
	"NULL78",
	"NULL79",
	"BLE_GATTS_EVT_WRITE",
	"BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST",
	"BLE_GATTS_EVT_SYS_ATTR_MISSING",
	"BLE_GATTS_EVT_HVC",
	"BLE_GATTS_EVT_SC_CONFIRM",
	"BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST",
	"BLE_GATTS_EVT_TIMEOUT",
	"BLE_GATTS_EVT_HVN_TX_COMPLETE",
	"NULL88"	
};

const char* nrf_ble_scan_evt[7] = {
	"NRF_BLE_SCAN_EVT_FILTER_MATCH",
	"NRF_BLE_SCAN_EVT_WHITELIST_REQUEST",
	"NRF_BLE_SCAN_EVT_WHITELIST_ADV_REPORT",
	"NRF_BLE_SCAN_EVT_NOT_FOUND",
	"NRF_BLE_SCAN_EVT_SCAN_TIMEOUT",
	"NRF_BLE_SCAN_EVT_CONNECTING_ERROR",
	"NRF_BLE_SCAN_EVT_CONNECTED"
};

const char* ble_nus_c_evt_type[3] = {
	"BLE_NUS_C_EVT_DISCOVERY_COMPLETE",
	"BLE_NUS_C_EVT_NUS_TX_EVT",
	"BLE_NUS_C_EVT_DISCONNECTED"
};

const char* ble_adv_evt_type[9] = {
	"BLE_ADV_EVT_IDLE",
	"BLE_ADV_EVT_DIRECTED_HIGH_DUTY",
	"BLE_ADV_EVT_DIRECTED",
	"BLE_ADV_EVT_FAST",
	"BLE_ADV_EVT_SLOW",
	"BLE_ADV_EVT_FAST_WHITELIST",
	"BLE_ADV_EVT_SLOW_WHITELIST",
	"BLE_ADV_EVT_WHITELIST_REQUEST",
	"BLE_ADV_EVT_PEER_ADDR_REQUEST",
};

const char* gap_roles[3] = {
	"BLE_GAP_ROLE_INVALID",
	"BLE_GAP_ROLE_PERIPH",
	"BLE_GAP_ROLE_CENTRAL"	
};

const char* hci_status_codes[0x3F] = {
	"BLE_HCI_STATUS_CODE_SUCCESS",
	"BLE_HCI_STATUS_CODE_UNKNOWN_BTLE_COMMAND",
	"BLE_HCI_STATUS_CODE_UNKNOWN_CONNECTION_IDENTIFIER",
	"/*Hardware Failure*/",
	"/*Page Timeout*/",
	"BLE_HCI_AUTHENTICATION_FAILURE",
	"BLE_HCI_STATUS_CODE_PIN_OR_KEY_MISSING",
	"BLE_HCI_MEMORY_CAPACITY_EXCEEDED",
	"BLE_HCI_CONNECTION_TIMEOUT",
	"/*Connection Limit Exceeded*/",
	"/*Synchronous Connection Limit To A Device Exceeded*/",
	"/*ACL Connection Already Exists*/",
	"BLE_HCI_STATUS_CODE_COMMAND_DISALLOWED",
	"/*Connection Rejected due to Limited Resources*/",
	"/*Connection Rejected Due To Security Reasons*/",
	"/*Connection Rejected due to Unacceptable BD_ADDR*/",
	"/*Connection Accept Timeout Exceeded*/",
	"/*Unsupported Feature or Parameter Value*/",
	"BLE_HCI_STATUS_CODE_INVALID_BTLE_COMMAND_PARAMETERS",
	"BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION",
	"BLE_HCI_REMOTE_DEV_TERMINATION_DUE_TO_LOW_RESOURCES",
	"BLE_HCI_REMOTE_DEV_TERMINATION_DUE_TO_POWER_OFF",
	"BLE_HCI_LOCAL_HOST_TERMINATED_CONNECTION",
	"/*Repeated Attempts*/",
	"/*Pairing Not Allowed*/",
	"/*Unknown LMP PDU*/",
	"BLE_HCI_UNSUPPORTED_REMOTE_FEATURE",
	"/*SCO Offset Rejected*/",
	"/*SCO Interval Rejected*/",
	"/*SCO Air Mode Rejected*/",
	"BLE_HCI_STATUS_CODE_INVALID_LMP_PARAMETERS",
	"BLE_HCI_STATUS_CODE_UNSPECIFIED_ERROR",
	"/*Unsupported LMP Parameter Value*/",
	"/*Role Change Not Allowed*/",
	"BLE_HCI_STATUS_CODE_LMP_RESPONSE_TIMEOUT",
	"BLE_HCI_STATUS_CODE_LMP_ERROR_TRANSACTION_COLLISION",
	"BLE_HCI_STATUS_CODE_LMP_PDU_NOT_ALLOWED",
	"/*Encryption Mode Not Acceptable*/",
	"/*Link Key Can Not be Changed*/",
	"/*Requested QoS Not Supported*/",
	"BLE_HCI_INSTANT_PASSED",
	"BLE_HCI_PAIRING_WITH_UNIT_KEY_UNSUPPORTED",
	"BLE_HCI_DIFFERENT_TRANSACTION_COLLISION",
	"/*Reserved*/",
	"/*QoS Unacceptable Parameter*/",
	"/*QoS Rejected*/",
	"/*Channel Classification Not Supported*/",
	"/*Insufficient Security*/",
	"BLE_HCI_PARAMETER_OUT_OF_MANDATORY_RANGE",
	"/*Reserved*/",
	"/*Role Switch Pending*/",
	"/*Reserved*/",
	"/*Reserved Slot Violation*/",
	"/*Role Switch Failed*/",
	"/*Extended Inquiry Response Too Large*/",
	"/*Secure Simple Pairing Not Supported By Host.*/",
	"/*Host Busy - Pairing*/",
	"/*Connection Rejected due to No Suitable Channel Found*/",
	"BLE_HCI_CONTROLLER_BUSY",
	"BLE_HCI_CONN_INTERVAL_UNACCEPTABLE",
	"BLE_HCI_DIRECTED_ADVERTISER_TIMEOUT",
	"BLE_HCI_CONN_TERMINATED_DUE_TO_MIC_FAILURE",
	"BLE_HCI_CONN_FAILED_TO_BE_ESTABLISHED"	
};

const char* uart_event_type[5] = {
	"APP_UART_DATA_READY",
	"APP_UART_FIFO_ERROR",
	"APP_UART_COMMUNICATION_ERROR",
	"APP_UART_TX_EMPTY",
	"APP_UART_DATA"
};

const char* nrfx_saadc_event_type[3] = {
	"NRFX_SAADC_EVT_DONE",
	"NRFX_SAADC_EVT_LIMIT",
	"NRFX_SAADC_EVT_CALIBRATEDONE"
};

const char* nus_event_type[4] = {
	"BLE_NUS_EVT_RX_DATA",
	"BLE_NUS_EVT_TX_RDY",
	"BLE_NUS_EVT_COMM_STARTED",
	"BLE_NUS_EVT_COMM_STOPPED"
};

const char* fds_event_type[6] = {
	"FDS_EVT_INIT",
    "FDS_EVT_WRITE",
    "FDS_EVT_UPDATE",
    "FDS_EVT_DEL_RECORD",
    "FDS_EVT_DEL_FILE",
    "FDS_EVT_GC"
};

/**< 使用时需要减去 NRF_ERROR_FDS_ERR_BASE */
const char* fds_error_type[15] = {
	"FDS_ERR_OPERATION_TIMEOUT",
	"FDS_ERR_NOT_INITIALIZED",
	"FDS_ERR_UNALIGNED_ADDR",
	"FDS_ERR_INVALID_ARG",
	"FDS_ERR_NULL_ARG",
	"FDS_ERR_NO_OPEN_RECORDS",
	"FDS_ERR_NO_SPACE_IN_FLASH",
	"FDS_ERR_NO_SPACE_IN_QUEUES",
	"FDS_ERR_RECORD_TOO_LARGE",
	"FDS_ERR_NOT_FOUND",
	"FDS_ERR_NO_PAGES",
	"FDS_ERR_USER_LIMIT_REACHED",
	"FDS_ERR_CRC_CHECK_FAILED",
	"FDS_ERR_BUSY",
	"FDS_ERR_INTERNAL"
};

